[package]
name = "magit-libgit2"
version = "0.1.0"
edition = "2018"
authors = ["Nguyễn Tuấn Anh <ubolonton@gmail.com>"]
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
emacs = { version = "0.7.0" }
git2 = "0.6"

[dev-dependencies]
emacs-rs-module = { version = "0.7.0" }
